// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpz26Uk7uK3Wn3RAUt4SiM5ZSGPCX9K8',
    appId: '1:112049537422:web:0da3963f7da7530a19e4df',
    messagingSenderId: '112049537422',
    projectId: 'ecommerce-multivendor-cd06c',
    authDomain: 'ecommerce-multivendor-cd06c.firebaseapp.com',
    storageBucket: 'ecommerce-multivendor-cd06c.appspot.com',
    measurementId: 'G-MKZ8E1Z46T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wcC2P9f_Nc6jp_Kf2O38HAD6px3r8QU',
    appId: '1:112049537422:android:532b8149511d671619e4df',
    messagingSenderId: '112049537422',
    projectId: 'ecommerce-multivendor-cd06c',
    storageBucket: 'ecommerce-multivendor-cd06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrd9yV-8pmmpLTOzOEs59KvQ8jNtiI1qQ',
    appId: '1:112049537422:ios:1d73eb0754c25b1119e4df',
    messagingSenderId: '112049537422',
    projectId: 'ecommerce-multivendor-cd06c',
    storageBucket: 'ecommerce-multivendor-cd06c.appspot.com',
    iosBundleId: 'com.example.userWebAppMultivendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrd9yV-8pmmpLTOzOEs59KvQ8jNtiI1qQ',
    appId: '1:112049537422:ios:4e5b7fd16d4caa3219e4df',
    messagingSenderId: '112049537422',
    projectId: 'ecommerce-multivendor-cd06c',
    storageBucket: 'ecommerce-multivendor-cd06c.appspot.com',
    iosBundleId: 'com.example.userWebAppMultivendor.RunnerTests',
  );
}
